project:
  type: website
  output-dir: docs
  
website:
  title: "MY WEB SITE"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
    tools:
      - icon: github
        href: https://github.com/ACC-UMASS/DACSS-604-Assignment-4.git
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2023, Alexandria Coombe"

format:
  html:
    theme: cerulean
    toc: true

editor: source

